Change User Class to use a primary constructor. Remove data annotations because those are handled by CreateUserViewModel which. Remove required keyword from Username and PreferredLanguage because it was causing error CS9035